services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ./setup:/tf/setup
      - ./setup:/tf/deploy
    working_dir: /tf
    environment:
      - AWS_ACCESS_KEY_ID=AKIATY7ORTGOQZI75O44
      - AWS_SECRET_ACCESS_KEY=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
