services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    working_dir: /tf
    environment:
      - AWS_ACCESS_KEY_ID= 
      - AWS_SECRET_ACCESS_KEY= 
      - AWS_DEFAULT_REGION = ap-south-1
      - AWS_WORKSPACE=${TF_WORKSPACE}
