services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ${PWD}/setup:/tf/setup
      - ${PWD}/deploy:/tf/deploy
    working_dir: /tf
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_WORKSPACE=default
